### ISSUE TITLE
Setting overwrite

### ISSUE THREAD

**Issue by Daiki48** [Daiki48/thumbgen#4]
If you run thumbgen init when there is already `allow_overwrite = true` in the `.thumbgen/config.toml` file, it will overwrite the default setting.
If false, leave the existing configuration items as they are and add only the missing items.

```toml

# This config is setup for thumbgen

[metas]
title = 'Hello. I love Rust language. Rust is best for programming. I writing Rust at thumbgen. My Github username is Daiki48.'
username = 'Daiki48'

[design]
background_color = [34, 39, 46, 255]
font_color = [102, 204, 202, 255]

# Add item
[setting]
allow_overwrite = false
```
